### ISSUE TITLE
Instructions on how to run

### ISSUE THREAD

**Issue by cifkao** [mengshor/PiRhDy#2]
Thanks for your work! Unfortunately, it is not clear how to run your code. Could you please provide some instructions, namely where to put data and what commands to run?

I assume I should go to each of the directories and run `run.py`, but it seems to require some pickle files that are not provided. It seems like they should be generated using `write_filenames`, but it's not clear how to call this function. Could you please add that information or provide the pickle files?

Thanks again!

**Comment by mengshor** [comment]
Sorry for the late reply!
Yes, it needs to use the run.py.
The pickle files are the lakh dataset, you can download it from https://colinraffel.com/projects/lmd/.I
If you have any further questions, please contact me via email (lianghongru@scu.edu.cn). I will reply as soon as possible.

**Comment by SkyAndCloud** [comment]
This link is not accessible

**Comment by mengshor** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
     Can u try one more time?
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Yong ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/20/2022 11:51
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            State ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [mengshor/PiRhDy] Instructions on how to run (Issue #2)
        
      
    
  
  
This link is not accessible

**Comment by SkyAndCloud** [comment]
The above link https://colinraffel.com/projects/lmd/.I is not accessible. I also tried to find it in https://colinraffel.com/projects/lmd
Sorry, I do not know which link the pickle-format lakh dataset is in [https://colinraffel.com/projects/lmd](https://colinraffel.com/projects/lmd)
